assets/plugins/jqwidgets/demos/asp.net-core-mvc-tag-helpers/Controllers/TagHelpersController.cs
using System.Linq;
using jQWidgets.AspNet.Core.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System;
using jQWidgets.AspNetCore.Mvc.TagHelpers;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http.Internal;

namespace jQWidgets.AspNet.Core.Controllers
{
    public class JSONData
    {
        public List<SalesEmployee> Employees
        {
            get;
            set;
        }
        public int TotalRecords
        {
            get;
            set;
        }
    }
    public class TagHelpersController : Controller
    {
        private jQWidgetsDemosContext _context;
        public TagHelpersController(jQWidgetsDemosContext context)
        {
            _context = context;
        }
        //
        // GET: /Widgets/
        public ActionResult Index()
        {
            return View("ScrollView/ScrollView");

            return View("ScrollView/ScrollView", _context.SalesEmployees);
        //    return View("DataTable/DataTableRowDetails", _context.Employee.ToList());
        }
        [HttpPost]
        public FileContentResult ExportData(FormPostBack data)
        { 
             return ExportHelper.ExportData(data);
        }

        [HttpPost]
        public string GetEmployees()
        {
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList(); 
            JSONData data = new JSONData();
            data.TotalRecords = allEmployees.Count;
            data.Employees = allEmployees;
            return JsonConvert.SerializeObject(data);
        }

        [HttpPost]
        public string GetChildren(string jsonData)
        {
            JToken token = JObject.Parse(jsonData);
            string id = (string)token.SelectToken("ID");
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList();
            JSONData data = new JSONData();
            List<SalesEmployee> employees = new List<SalesEmployee>();
            for (int i = 0; i < allEmployees.Count; i++)
            {
                if (String.IsNullOrEmpty(id))
                {
                    if (i < 5)
                    {
                        employees.Add(allEmployees[i]);
                    }
                }
                else
                {
                    if (allEmployees[i].ReportsTo == Int32.Parse(id))
                    {
                        employees.Add(allEmployees[i]);
                    }
                }
            }
            data.TotalRecords = allEmployees.Count;
            data.Employees = employees;
            return JsonConvert.SerializeObject(data);
        }

        [HttpPost]
        public string GetPageData(string jsonData)
        {
            JToken token = JObject.Parse(jsonData);

            List<JToken> filterGroups = token.SelectToken("filterGroups").Children().ToList();
            int pageSize = (int)token.SelectToken("pagesize");
            int pageNum = (int)token.SelectToken("pagenum");
            string sortField = (string)token.SelectToken("sortdatafield");
            string sortOrder = (string)token.SelectToken("sortorder");
            int count = 0;
            List<SalesEmployee> employees = new List<SalesEmployee>();
            List<SalesEmployee> allEmployees = _context.SalesEmployees.ToList();
            if (sortField != "")
            {
                if (sortOrder == "asc")
                {              
                    allEmployees = (from p in allEmployees
                                    orderby (p.GetType().GetProperty(sortField).GetValue(p))
                                 select p).ToList();

                }
                else if (sortOrder == "desc")
                {
                    allEmployees = (from p in allEmployees
                                    orderby (p.GetType().GetProperty(sortField).GetValue(p)) descending
                                    select p).ToList();
                }
            }
            if (filterGroups.Count > 0)
            {
                List<SalesEmployee> filteredEmployees = allEmployees;
                for (int j = 0; j < filterGroups.Count; j++)
                {
                    List<JToken> filters = filterGroups[j].SelectToken("filters").Children().ToList();

                    List<SalesEmployee> filterGroup = filteredEmployees;
                    List<SalesEmployee> filterGroupResult = new List<SalesEmployee>();
                    for (int i = 0; i < filters.Count; i++)
                    {
                        string filterLabel = (string)filters[i].SelectToken("label");
                        string filterValue = (string)filters[i].SelectToken("value");
                        string filterDataField = (string)filters[i].SelectToken("field");
                        string filterCondition = (string)filters[i].SelectToken("condition");
                        string filterType = (string)filters[i].SelectToken("type");
                        string filterOperator = (string)filters[i].SelectToken("operator");

                        List<SalesEmployee> currentResult = new List<SalesEmployee>();

                        switch (filterCondition)
                        {
                            case "NOT_EMPTY":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)) != null)
                                                     select p).ToList();
                                break;
                            case "NOT_NULL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() != "")
                                                     select p).ToList();
                                break;
                            case "NULL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)) == null)
                                                     select p).ToList();
                                break;
                            case "EMPTY":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() == "")
                                                     select p).ToList();
                                break;
                            case "CONTAINS_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().Contains(filterValue))
                                                     select p).ToList();
                                break;
                            case "CONTAINS":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) != -1)
                                                     select p).ToList();
                                break;
                            case "DOES_NOT_CONTAIN_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where (!(p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().Contains(filterValue))
                                                     select p).ToList();
                                break;
                            case "DOES_NOT_CONTAIN":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) == -1)
                                                     select p).ToList();
                                break;
                            case "EQUAL_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() == filterValue)
                                                     select p).ToList();
                                break;
                            case "EQUAL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) == 0)
                                                     select p).ToList();
                                break;
                            case "NOT_EQUAL_CASE_SENSITIVE":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString() != filterValue)
                                                     select p).ToList();
                                break;
                            case "NOT_EQUAL":
                                currentResult = (from p in filterGroup
                                                 where ((p.GetType().GetProperty(filterDataField).GetValue(p)).ToString().IndexOf(filterValue, StringComparison.CurrentCultureIgnoreCase) != 0)
                                                     select p).ToList();
                                break;
                            case "GREATER_THAN":
                                currentResult = (from p in filterGroup

assets/plugins/jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/Scheduler/Scheduler.cshtml
@model jQWidgets.AspNet.Core.Models.jQWidgetsDemosContext
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC Scheduler Example";
}
<label>ASP .NET Core MVC Scheduler Tag Helper Example</label><br/><br/>
<jqx-scheduler source="Model.Appointments" showLegend="true" view="WeekView" resources="Model.Resources" appointmentDataFields="Model.AppointmentDataFields" theme="@ViewData["Theme"]"  date="Model.Date" width="850" height="600">
    <jqx-scheduler-views>
        <jqx-scheduler-view type="DayView"></jqx-scheduler-view>
        <jqx-scheduler-view type="WeekView"></jqx-scheduler-view>
        <jqx-scheduler-view type="MonthView"></jqx-scheduler-view>
    </jqx-scheduler-views>
</jqx-scheduler>

assets/plugins/jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/Scheduler/SchedulerServerProcessing.cshtml
@model jQWidgets.AspNet.Core.Models.jQWidgetsDemosContext
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC Scheduler Server Example";
}
<label>ASP .NET Core MVC Scheduler Server Processing Example</label><br/><br/>
<jqx-scheduler source="Model.Appointments" showLegend="true" view="WeekView" create="@Url.Action("AddAppointment","TagHelpers")" delete="@Url.Action("DeleteAppointment","TagHelpers")" edit="@Url.Action("EditAppointment","TagHelpers")" resources="Model.Resources" appointmentDataFields="Model.AppointmentDataFields" theme="@ViewData["Theme"]"  date="Model.Date" width="850" height="600">
    <jqx-scheduler-views>
        <jqx-scheduler-view type="DayView"></jqx-scheduler-view>
        <jqx-scheduler-view type="WeekView"></jqx-scheduler-view>
        <jqx-scheduler-view type="MonthView"></jqx-scheduler-view>
    </jqx-scheduler-views>
</jqx-scheduler>

assets/plugins/jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/Scheduler/SchedulerTimeRuler.cshtml
@model jQWidgets.AspNet.Core.Models.jQWidgetsDemosContext
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC Scheduler TimeZones Example";
    List<SchedulerTimeZone> timeZones = new List<SchedulerTimeZone>() { new SchedulerTimeZone() { ID = "UTC", Text = "UTC" }, new SchedulerTimeZone() { ID = "Pacific Standard Time", Text = "PST" } };
}
<script>
    var timeZones = [{ id: "UTC", text: "UTC" }, { id: "Pacific Standard Time", text: "PST" }];
</script>
<label>ASP .NET Core MVC ComboBox Example</label><br/><br/>
<jqx-scheduler source="Model.Appointments" showLegend="true" view="WeekView" resources="Model.Resources" appointmentDataFields="Model.AppointmentDataFields" theme="@ViewData["Theme"]"  date="Model.Date" width="850" height="600">
    <jqx-scheduler-views>
        <jqx-scheduler-view type="DayView">
            <jqx-scheduler-time-ruler timeZones="timeZones"></jqx-scheduler-time-ruler>
        </jqx-scheduler-view>
        <jqx-scheduler-view type="WeekView">
            <jqx-scheduler-time-ruler timeZones="timeZones"></jqx-scheduler-time-ruler>
        </jqx-scheduler-view>
        <jqx-scheduler-view type="MonthView"></jqx-scheduler-view>
    </jqx-scheduler-views>
</jqx-scheduler>

assets/plugins/jqwidgets/demos/asp.net-core-mvc-tag-helpers/Views/TagHelpers/Scheduler/SchedulerTimelineViews.cshtml
@model jQWidgets.AspNet.Core.Models.jQWidgetsDemosContext
@using jQWidgets.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "ASP .NET MVC Scheduler TimelineViews Example";
}
<label>ASP .NET Core MVC Scheduler TimelineViews Example</label><br/><br/>
<jqx-scheduler source="Model.Appointments" showLegend="true" view="TimelineWeekView" resources="Model.Resources" appointmentDataFields="Model.AppointmentDataFields" theme="@ViewData["Theme"]"  date="Model.Date" width="850" height="600">
    <jqx-scheduler-views>
        <jqx-scheduler-view type="TimelineDayView"></jqx-scheduler-view>
        <jqx-scheduler-view type="TimelineWeekView"></jqx-scheduler-view>
        <jqx-scheduler-view type="TimelineMonthView" ></jqx-scheduler-view>
    </jqx-scheduler-views>
</jqx-scheduler>